package com.eusa.domain;

// Generated 30/06/2012 05:12:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private Long id;
	private long version;
	private String apellidom;
	private String apellidop;
	private String correo;
	private String nombres;
	private String puesto;

	public Persona() {
	}

	public Persona(String apellidom, String apellidop, String correo,
			String nombres, String puesto) {
		this.apellidom = apellidom;
		this.apellidop = apellidop;
		this.correo = correo;
		this.nombres = nombres;
		this.puesto = puesto;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	public String getApellidom() {
		return this.apellidom;
	}

	public void setApellidom(String apellidom) {
		this.apellidom = apellidom;
	}

	public String getApellidop() {
		return this.apellidop;
	}

	public void setApellidop(String apellidop) {
		this.apellidop = apellidop;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

}
